server:
  port: 8080
  servlet:
    contextPath: /v1/flight-booking

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flight_booking
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  liquibase:
    change-log: classpath:/db/dbchanges_master.yaml

logging:
  level:
    liquibase: INFO
